version: '3.8'
services:
  pgdatabase:
    image: postgres:13
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
    networks:
      - pgnetwork

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ubiorukevwe@gmail.com
      PGADMIN_DEFAULT_PASSWORD: rootubio
      PGADMIN_PREFERRED_URL_SCHEME: 'https'
    ports:
      - "8080:80"
    depends_on:
      - pgdatabase
    networks:
      - pgnetwork

networks:
  pgnetwork:
    driver: bridge
